### ISSUE TITLE
how many epoches you set when you train

### ISSUE THREAD

**Issue by zhangyunming** [yangxy/GPEN#10]
nice work ,

how many epoches you set when you train, and what GPUs you used and how long time

**Comment by yangxy** [comment]
I trained on a P100 GPU. It usually took more than 10 days for finetuning.

**Comment by zimenglan-sysu-512** [comment]
hi @yangxy 
i use 4 A100 GPUs to simply run train_simple.sh to train from scratch, it takes long time to finish as below:
d: 1.1789; g: 1.0828; r1: 0.0001; :   0%|          246/4000000 [07:47<2060:16:16,  1.85s/it]
does it work normally?
thanks.
