### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'int' and 'str'

### ISSUE THREAD

**Issue by netrunner-exe** [yangxy/GPEN#103]
Traceback (most recent call last):
  File "face_enhancement.py", line 138, in <module>
    faceenhancer = FaceEnhancement(in_size=args.in_size, out_size=args.out_size, model=args.model, use_sr=args.use_sr, sr_model=args.sr_model, channel_multiplier=args.channel_multiplier, narrow=args.narrow, key=args.key, device='cuda' if args.use_cuda else 'cpu')
  File "face_enhancement.py", line 22, in __init__
    self.facegan = FaceGAN(base_dir, in_size, out_size, model, channel_multiplier, narrow, key, device=device)
  File "/content/GPEN/face_model/face_gan.py", line 17, in __init__
    self.mfile = os.path.join(base_dir, 'weights', model+'.pth')
TypeError: unsupported operand type(s) for +: 'int' and 'str'

**Comment by osushiski** [comment]
@netrunner-exe I had this error too.
If you just want to try GPEN, why don't you try modifying the code as follows?
```
!git clone https://github.com/yangxy/GPEN.git
%cd /content/GPEN
!git checkout 408b9ca3f0853a95a582455bd1d8ef5fa07a23b4
```
It just recalls the version before the error occurred.
