### ISSUE TITLE
Visible rectange on faces pasted are back

### ISSUE THREAD

**Issue by FlowDownTheRiver** [yangxy/GPEN#108]
Hi there thank you for the updates.Especially for the 2048 model.
I have a few questions and some sort of request...

When gpen was released it was producing visible rectange areas when the enhanced faces are pasted back to original picture.Then you have updated the code and smooth the area.Then they disappeared,giving much pleasable results.But now the code changed the rectange region appears on the results again.Can we have the older clean paste behaviour back without rectanges visible for the updated code?

About --insize, I understand it is the model resolution we are using from the code and command line options.So 512 model uses 512 insize,2048 model 2048.How about the --outsize? I couldn't see a visual difference when I tried fro example 2048 model and 256 outsize compared to outsize of 2048.Is this not implemented yet?

Another question I have is what is the right way of outputting a 4x output whether we use 512 model or 2048.When I set the --sr_scale 4 ,it is still outputting 2x, but only when I uncomment this line : im = cv2.resize(im, (0,0), fx=2, fy=2) # optional it outputs a 4x image.Is this the right way of getting 4x images "natively" or it outputs 2x image and just resizes the 2x result by 2.Can you make it clear how to get 4x results?

Also in some cases when the images gets larger beyond some resolution,background enhancement disables itself.How to force background enhancement work no matter what?

Some optional requests : Do we have any type of control about the background enhancement model,like denoise less?
Do we have any chance realesrgan model used in Gfpgan to be implemented to Gpen as an option?It gives less denoised output.

**Comment by yangxy** [comment]
1. https://github.com/yangxy/GPEN/blob/e15361582faa17117bd1a8edecdfc4c72e74b599/face_enhancement.py#L88-L89
Replace L89 with L88.

2. Not implemented yet and so is ``sr_scale``.

3. https://github.com/yangxy/GPEN/blob/e15361582faa17117bd1a8edecdfc4c72e74b599/sr_model/real_esrnet.py#L15
The sr model ``rrdb_realesrnet_psnr``  is x2. Replace it with your own x4 sr model. I will provide one soon.

4. Do not set ``--use_cuda``. 

5. Maybe. I am not sure.

**Comment by blessedcoolant** [comment]
> 1. https://github.com/yangxy/GPEN/blob/e15361582faa17117bd1a8edecdfc4c72e74b599/face_enhancement.py#L88-L89
>    
>    Replace L89 with L88.

This fixes it.

**Comment by FlowDownTheRiver** [comment]
Thank you very much for answering all and for your time.
