### ISSUE TITLE
Problem with my package

### ISSUE THREAD

**Issue by Cioscos** [yangxy/GPEN#110]
Hi!
As you know I shared my stand-alone GPEN-Windows edition, but I've a problem with new update.
First important thing, I don't want to use demo.py in my package for my reasons. But the problem is not that. I'll post screens of the error.
I start GPEN using this command line:
```
python face_enhancement.py --model GPEN-BFR-2048 --in_size 2048 --use_cuda --aligned
```
**First important question**: how do in_size and out_size parameter work? What's their function? Is it correct to use in_size in this way?

Anyway, when I try to run GPEN with this command, Pytorch rises this error reading the model dictionary I guess:
```
Traceback (most recent call last):
  File "face_enhancement.py", line 226, in <module>
    main()
  File "face_enhancement.py", line 177, in main
    device='cuda' if args.use_cuda else 'cpu'
  File "face_enhancement.py", line 27, in __init__
    self.facegan = FaceGAN(base_dir, in_size, out_size, model, channel_multiplier, narrow, key, device=device)
  File "U:\DeepFake_softwares\GPEN-Windows\face_model\face_gan.py", line 24, in __init__
    self.load_model(channel_multiplier, narrow)
  File "U:\DeepFake_softwares\GPEN-Windows\face_model\face_gan.py", line 33, in load_model
    self.model.load_state_dict(pretrained_dict)
  File "U:\DeepFake_softwares\GPEN-Windows\_internal\Python37\lib\site-packages\torch\nn\modules\module.py", line 1407, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for FullGenerator_SR:
        Unexpected key(s) in state_dict: "generator.convs.14.conv.weight", "generator.convs.14.conv.blur.kernel", "generator.convs.14.conv.modulation.weight", "generator.convs.14.conv.modulation.bias", "generator.convs.14.noise.weight", "generator.convs.14.activate.bias", "generator.convs.15.conv.weight", "generator.convs.15.conv.modulation.weight", "generator.convs.15.conv.modulation.bias", "generator.convs.15.noise.weight", "generator.convs.15.activate.bias", "generator.convs.16.conv.weight", "generator.convs.16.conv.blur.kernel", "generator.convs.16.conv.modulation.weight", "generator.convs.16.conv.modulation.bias", "generator.convs.16.noise.weight", "generator.convs.16.activate.bias", "generator.convs.17.conv.weight", "generator.convs.17.conv.modulation.weight", "generator.convs.17.conv.modulation.bias", "generator.convs.17.noise.weight", "generator.convs.17.activate.bias", "generator.to_rgbs.7.bias", "generator.to_rgbs.7.upsample.kernel", "generator.to_rgbs.7.conv.weight", "generator.to_rgbs.7.conv.modulation.weight", "generator.to_rgbs.7.conv.modulation.bias", "generator.to_rgbs.8.bias", "generator.to_rgbs.8.upsample.kernel", "generator.to_rgbs.8.conv.weight", "generator.to_rgbs.8.conv.modulation.weight", "generator.to_rgbs.8.conv.modulation.bias".
```
When I use 512 model, everything is good.

Could you help me to understand what is the problem?

**Comment by yangxy** [comment]
https://github.com/yangxy/GPEN/blob/e15361582faa17117bd1a8edecdfc4c72e74b599/face_model/face_gan.py#L22

You should set ``out_size`` to be ``None`` or the same value of ``in_size`` as follows:

https://github.com/yangxy/GPEN/blob/e15361582faa17117bd1a8edecdfc4c72e74b599/face_enhancement.py#L15-L16

 ``out_size`` is new.

**Comment by yangxy** [comment]
Update ``gpen_model.py`` too.

**Comment by Cioscos** [comment]
Thank you for the quick reply. I can't believe how much my mistake was stupid. The default value of out_size was 512 and not None. I fixed, now it works. Thank you very much.

**Comment by Cioscos** [comment]
Is in_size the size of input images?

**Comment by yangxy** [comment]
> Is in_size the size of input images?

Yep~

**Comment by Cioscos** [comment]
> > Is in_size the size of input images?
> 
> Yep~

So, can I enhance a 512x image with 2048 model?

**Comment by yangxy** [comment]
> 

Of course you can. Note that the 2048 model may not work well on severely degraded faces.

**Comment by Cioscos** [comment]
> > 
> 
> Of course you can. Note that the 2048 model may not work well on severely degraded faces.

So we must specify everytime in_size param? What if in the folder I've different images of several different resolutions?
Talking aboit out_res, it just resizes the product of the gpen model, not eventually the entire frame I guess.
Anyway yes with tests I noticed that 2048 model is very good to improve already good images.

**Comment by yangxy** [comment]
1. ``in_size`` has nothing to do with the image resolution. It's all about the model.

2. please read the source code.
