### ISSUE TITLE
Request for super resolution models

### ISSUE THREAD

**Issue by FlowDownTheRiver** [yangxy/GPEN#115]
For 2x and 4x models I am getting this kind of error .
sr failed: CUDA out of memory. Tried to allocate 2.14 GiB (GPU 0; 11.00 GiB total capacity; 3.89 GiB already allocated; 1.63 GiB free; 7.85 GiB reserved in total by PyTorch)
pytorch is going going out of memory with a 1080 ti.This happens when the resolution of the image is around 2k.The face model does its job anyway.So most of the time unless the image resolution is low,this limits the super resolution.

On gfpgan they are using tiles processing for super resolution.So it doesn't go out of memory and it delivers high resolution by dividing the picture into smaller chunks.Is it possible for Gpen to achieve the same kind of behaviour?

**Comment by yangxy** [comment]
Thanks for the advice. Will be added very soon.

**Comment by FlowDownTheRiver** [comment]
> Thanks for the advice. Will be added very soon.

Thank you very much for the code update.I have been waiting for this for a very long time.
