### ISSUE TITLE
confused of train strategy

### ISSUE THREAD

**Issue by wooooyo** [yangxy/GPEN#118]
I'm confused about the train strategy. In the paper, author said first pre-trained the GAN prior network and then the GPEN.
What I want to know is whether or not I need to pretrain GAN and then train GPEN seperately, because I can see your train example only one step in train_simple.py.

**Comment by lmvgjp** [comment]
hi @wooooyo, i am also a bit confused...how did you perform your training experiments?
thanks!

**Comment by zimenglan-sysu-512** [comment]
+1

**Comment by joe-zxh** [comment]
The author explain here:
https://github.com/yangxy/GPEN/issues/8#issuecomment-856705571
