### ISSUE TITLE
预训练模型问题

### ISSUE THREAD

**Issue by yumulinfeng1** [yangxy/GPEN#147]
如下
`    if args.pretrain is not None:
        print('load model:', args.pretrain)
        
        ckpt = torch.load(args.pretrain)

        generator.load_state_dict(ckpt['g'])
        discriminator.load_state_dict(ckpt['d'])
        g_ema.load_state_dict(ckpt['g_ema'])
            
        g_optim.load_state_dict(ckpt['g_optim'])
        d_optim.load_state_dict(ckpt['d_optim'])`

那个预训练模型包含了 g   d      g_ema      g_optim      d_optim这些？？

怎么用预训练模型？
比如我想训练insize：256的 ，设置GPEN-BFR-256.pth为预训练模型是报错的

**Comment by YueChao-98** [comment]
请问你最后怎么解决的？
