### ISSUE TITLE
Runtime error happened when running face_colorization.py.

### ISSUE THREAD

**Issue by suoych** [yangxy/GPEN#17]
Hi, I just want to run the demo to see the effect on my machine and I got the result below.

Traceback (most recent call last):
  File "/home/suoych/.local/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1672, in _run_ninja_build
    env=env)
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "face_colorization.py", line 12, in <module>
    from face_model.face_gan import FaceGAN
  File "/home/suoych/GPEN/face_model/face_gan.py", line 13, in <module>
    from model import FullGenerator
  File "/home/suoych/GPEN/face_model/model.py", line 15, in <module>
    from op import FusedLeakyReLU, fused_leaky_relu, upfirdn2d
  File "/home/suoych/GPEN/face_model/op/__init__.py", line 1, in <module>
    from .fused_act import FusedLeakyReLU, fused_leaky_relu
  File "/home/suoych/GPEN/face_model/op/fused_act.py", line 14, in <module>
    os.path.join(module_path, 'fused_bias_act_kernel.cu'),
  File "/home/suoych/.local/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1092, in load
    keep_intermediates=keep_intermediates)
  File "/home/suoych/.local/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1303, in _jit_compile
    is_standalone=is_standalone)
  File "/home/suoych/.local/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1408, in _write_ninja_file_and_build_library
    error_prefix=f"Error building extension '{name}'")
  File "/home/suoych/.local/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1682, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension 'fused': [1/2] :/usr/local/cuda-11.2/bin/nvcc  -DTORCH_EXTENSION_NAME=fused -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/suoych/.local/lib/python3.6/site-packages/torch/include -isystem /home/suoych/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -isystem /home/suoych/.local/lib/python3.6/site-packages/torch/include/TH -isystem /home/suoych/.local/lib/python3.6/site-packages/torch/include/THC -isystem :/usr/local/cuda-11.2/include -isystem /usr/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_61,code=compute_61 -gencode=arch=compute_61,code=sm_61 --compiler-options '-fPIC' -std=c++14 -c /home/suoych/GPEN/face_model/op/fused_bias_act_kernel.cu -o fused_bias_act_kernel.cuda.o
FAILED: fused_bias_act_kernel.cuda.o
:/usr/local/cuda-11.2/bin/nvcc  -DTORCH_EXTENSION_NAME=fused -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/suoych/.local/lib/python3.6/site-packages/torch/include -isystem /home/suoych/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -isystem /home/suoych/.local/lib/python3.6/site-packages/torch/include/TH -isystem /home/suoych/.local/lib/python3.6/site-packages/torch/include/THC -isystem :/usr/local/cuda-11.2/include -isystem /usr/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_61,code=compute_61 -gencode=arch=compute_61,code=sm_61 --compiler-options '-fPIC' -std=c++14 -c /home/suoych/GPEN/face_model/op/fused_bias_act_kernel.cu -o fused_bias_act_kernel.cuda.o
/bin/sh: 1: :/usr/local/cuda-11.2/bin/nvcc: not found
ninja: build stopped: subcommand failed.

I got GPU on my machine and my python version is 3.6, torch version 1.9, CUDA version 10.2, GCC version 7.5. I also checked the $PATH and the nvcc path is included.

It would be great if someone could help me with the problem. Thanks so much!

**Comment by yangxy** [comment]
> Hi, I just want to run the demo to see the effect on my machine and I got the result below.
> 
> Traceback (most recent call last):
> File "/home/suoych/.local/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1672, in _run_ninja_build
> env=env)
> File "/usr/lib/python3.6/subprocess.py", line 438, in run
> output=stdout, stderr=stderr)
> subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
> File "face_colorization.py", line 12, in
> from face_model.face_gan import FaceGAN
> File "/home/suoych/GPEN/face_model/face_gan.py", line 13, in
> from model import FullGenerator
> File "/home/suoych/GPEN/face_model/model.py", line 15, in
> from op import FusedLeakyReLU, fused_leaky_relu, upfirdn2d
> File "/home/suoych/GPEN/face_model/op/**init**.py", line 1, in
> from .fused_act import FusedLeakyReLU, fused_leaky_relu
> File "/home/suoych/GPEN/face_model/op/fused_act.py", line 14, in
> os.path.join(module_path, 'fused_bias_act_kernel.cu'),
> File "/home/suoych/.local/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1092, in load
> keep_intermediates=keep_intermediates)
> File "/home/suoych/.local/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1303, in _jit_compile is_standalone=is_standalone) File "/home/suoych/.local/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1408, in _write_ninja_file_and_build_library error_prefix=f"Error building extension '{name}'") File "/home/suoych/.local/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1682, in _run_ninja_build raise RuntimeError(message) from e RuntimeError: Error building extension 'fused': [1/2] :/usr/local/cuda-11.2/bin/nvcc -DTORCH_EXTENSION_NAME=fused -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE="_gcc" -DPYBIND11_STDLIB="_libstdcpp" -DPYBIND11_BUILD_ABI="_cxxabi1011" -isystem /home/suoych/.local/lib/python3.6/site-packages/torch/include -isystem /home/suoych/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -isystem /home/suoych/.local/lib/python3.6/site-packages/torch/include/TH -isystem /home/suoych/.local/lib/python3.6/site-packages/torch/include/THC -isystem :/usr/local/cuda-11.2/include -isystem /usr/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_61,code=compute_61 -gencode=arch=compute_61,code=sm_61 --compiler-options '-fPIC' -std=c++14 -c /home/suoych/GPEN/face_model/op/fused_bias_act_kernel.cu -o fused_bias_act_kernel.cuda.o
> FAILED: fused_bias_act_kernel.cuda.o
> :/usr/local/cuda-11.2/bin/nvcc -DTORCH_EXTENSION_NAME=fused -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE="_gcc" -DPYBIND11_STDLIB="_libstdcpp" -DPYBIND11_BUILD_ABI="_cxxabi1011" -isystem /home/suoych/.local/lib/python3.6/site-packages/torch/include -isystem /home/suoych/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -isystem /home/suoych/.local/lib/python3.6/site-packages/torch/include/TH -isystem /home/suoych/.local/lib/python3.6/site-packages/torch/include/THC -isystem :/usr/local/cuda-11.2/include -isystem /usr/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_61,code=compute_61 -gencode=arch=compute_61,code=sm_61 --compiler-options '-fPIC' -std=c++14 -c /home/suoych/GPEN/face_model/op/fused_bias_act_kernel.cu -o fused_bias_act_kernel.cuda.o
> /bin/sh: 1: :/usr/local/cuda-11.2/bin/nvcc: not found
> ninja: build stopped: subcommand failed.
> 
> I got GPU on my machine and my python version is 3.6, torch version 1.9, CUDA version 10.2, GCC version 7.5. I also checked the $PATH and the nvcc path is included.
> 
> It would be great if someone could help me with the problem. Thanks so much!

**/usr/local/cuda-11.2/bin/nvcc: not found**

**Comment by suoych** [comment]
> > Hi, I just want to run the demo to see the effect on my machine and I got the result below.
> > Traceback (most recent call last):
> > File "/home/suoych/.local/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1672, in _run_ninja_build
> > env=env)
> > File "/usr/lib/python3.6/subprocess.py", line 438, in run
> > output=stdout, stderr=stderr)
> > subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
> > The above exception was the direct cause of the following exception:
> > Traceback (most recent call last):
> > File "face_colorization.py", line 12, in
> > from face_model.face_gan import FaceGAN
> > File "/home/suoych/GPEN/face_model/face_gan.py", line 13, in
> > from model import FullGenerator
> > File "/home/suoych/GPEN/face_model/model.py", line 15, in
> > from op import FusedLeakyReLU, fused_leaky_relu, upfirdn2d
> > File "/home/suoych/GPEN/face_model/op/**init**.py", line 1, in
> > from .fused_act import FusedLeakyReLU, fused_leaky_relu
> > File "/home/suoych/GPEN/face_model/op/fused_act.py", line 14, in
> > os.path.join(module_path, 'fused_bias_act_kernel.cu'),
> > File "/home/suoych/.local/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1092, in load
> > keep_intermediates=keep_intermediates)
> > File "/home/suoych/.local/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1303, in _jit_compile is_standalone=is_standalone) File "/home/suoych/.local/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1408, in _write_ninja_file_and_build_library error_prefix=f"Error building extension '{name}'") File "/home/suoych/.local/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1682, in _run_ninja_build raise RuntimeError(message) from e RuntimeError: Error building extension 'fused': [1/2] :/usr/local/cuda-11.2/bin/nvcc -DTORCH_EXTENSION_NAME=fused -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE="_gcc" -DPYBIND11_STDLIB="_libstdcpp" -DPYBIND11_BUILD_ABI="_cxxabi1011" -isystem /home/suoych/.local/lib/python3.6/site-packages/torch/include -isystem /home/suoych/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -isystem /home/suoych/.local/lib/python3.6/site-packages/torch/include/TH -isystem /home/suoych/.local/lib/python3.6/site-packages/torch/include/THC -isystem :/usr/local/cuda-11.2/include -isystem /usr/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_61,code=compute_61 -gencode=arch=compute_61,code=sm_61 --compiler-options '-fPIC' -std=c++14 -c /home/suoych/GPEN/face_model/op/fused_bias_act_kernel.cu -o fused_bias_act_kernel.cuda.o
> > FAILED: fused_bias_act_kernel.cuda.o
> > :/usr/local/cuda-11.2/bin/nvcc -DTORCH_EXTENSION_NAME=fused -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE="_gcc" -DPYBIND11_STDLIB="_libstdcpp" -DPYBIND11_BUILD_ABI="_cxxabi1011" -isystem /home/suoych/.local/lib/python3.6/site-packages/torch/include -isystem /home/suoych/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -isystem /home/suoych/.local/lib/python3.6/site-packages/torch/include/TH -isystem /home/suoych/.local/lib/python3.6/site-packages/torch/include/THC -isystem :/usr/local/cuda-11.2/include -isystem /usr/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_61,code=compute_61 -gencode=arch=compute_61,code=sm_61 --compiler-options '-fPIC' -std=c++14 -c /home/suoych/GPEN/face_model/op/fused_bias_act_kernel.cu -o fused_bias_act_kernel.cuda.o
> > /bin/sh: 1: :/usr/local/cuda-11.2/bin/nvcc: not found
> > ninja: build stopped: subcommand failed.
> > I got GPU on my machine and my python version is 3.6, torch version 1.9, CUDA version 10.2, GCC version 7.5. I also checked the $PATH and the nvcc path is included.
> > It would be great if someone could help me with the problem. Thanks so much!
> 
> **/usr/local/cuda-11.2/bin/nvcc: not found**

![image](https://user-images.githubusercontent.com/29878050/124535153-3e598d80-de48-11eb-889a-d3f33250d180.png)
 I already had it on the machine.

**Comment by suoych** [comment]
I finally solved the problem by downgrading cuda to 10.2.
