### ISSUE TITLE
🔥发现如下两个问题🔥

### ISSUE THREAD

**Issue by yfq512** [yangxy/GPEN#20]
1. 某些图片识别出错，输出的图像和输入图像一毛一样；
2.某些 人脸识别不准，放着明显的脸不找，偏偏在头发、眼睛等位置硬生生搞出人脸的轮廓；
针对以上情况，作者有好的解决办法么？

**Comment by yangxy** [comment]
> 1. 某些图片识别出错，输出的图像和输入图像一毛一样；
>    2.某些 人脸识别不准，放着明显的脸不找，偏偏在头发、眼睛等位置硬生生搞出人脸的轮廓；
>    针对以上情况，作者有好的解决办法么？

第一个问题是没有检测到人脸；第二个问题是人脸识别出错。可以考虑换一个更好的人脸检测模型来解决

**Comment by yfq512** [comment]
> > 1. 某些图片识别出错，输出的图像和输入图像一毛一样；
> >    2.某些 人脸识别不准，放着明显的脸不找，偏偏在头发、眼睛等位置硬生生搞出人脸的轮廓；
> >    针对以上情况，作者有好的解决办法么？
> 
> 第一个问题是没有检测到人脸；第二个问题是人脸识别出错。可以考虑换一个更好的人脸检测模型来解
