### ISSUE TITLE
Black spots on the face & Inference without insightface

### ISSUE THREAD

**Issue by ykk648** [yangxy/GPEN#21]
1.I tried GPEN in some low-res face-swap pics, find that black spots always show on generated faces, the lines of the face become deeper, makes face not real enough.
2.I modified GPEN codes, find that inference without insightface (but used mediapipe regardless the crop rule), the results also looks good to me.

Just share my using feeling, thx for your codes.

**Comment by yangxy** [comment]
The black spots problems are introduced due to our data degradation process, and are now solved. I will release the new model soon if necessary.

**Comment by andrewkuo** [comment]
@yangxy I am seeing some issues with black spots on the face as well. Have you released the new model yet? If so, where can I find it?

@ykk648 Can you share what you did to modify GPEN to fix this issue for you?

**Comment by ykk648** [comment]
@andrewkuo  try new 512/2048 res model, the results seems good enough for me.
