### ISSUE TITLE
Alternative model links?

### ISSUE THREAD

**Issue by 3BBUAE** [yangxy/GPEN#30]
Are there any alternative download links for the models?
Unfortunately the download speed is very slow for me, and I am sure I have fast internet.

**Comment by yangxy** [comment]
> Are there any alternative download links for the models?
> Unfortunately the download speed is very slow for me, and I am sure I have fast internet.
Try this https://drive.google.com/file/d/1g29lVHS3AvIhKudLjSJ9cfjuEQza3JOA/view?usp=sharing

**Comment by 3BBUAE** [comment]
This worked perfectly thank you.
Is it possible to share the other models as well, I would like to experiment with the inpainting and face restoration.

**Comment by yangxy** [comment]
> This worked perfectly thank you.
> Is it possible to share the other models as well, I would like to experiment with the inpainting and face restoration.

I don't have enough spare space on my google drive. Sorry about that.
