### ISSUE TITLE
应用于视频

### ISSUE THREAD

**Issue by ShiqiLi047** [yangxy/GPEN#31]
这个效果非常好，我在测试的时候发现人脸增强应用于视频，会有人脸临近帧某些位置不一致问题即人脸抖动，请问关于这种现在有什么解决方案吗？谢谢大佬～

**Comment by yangxy** [comment]
> 这个效果非常好，我在测试的时候发现人脸增强应用于视频，会有人脸临近帧某些位置不一致问题即人脸抖动，请问关于这种现在有什么解决方案吗？谢谢大佬～

可以考虑用人脸分割的mask来替换代码中使用的mask，最小化人脸区域外像素的影响

**Comment by ShiqiLi047** [comment]
> > 这个效果非常好，我在测试的时候发现人脸增强应用于视频，会有人脸临近帧某些位置不一致问题即人脸抖动，请问关于这种现在有什么解决方案吗？谢谢大佬～
> 
> 可以考虑用人脸分割的mask来替换代码中使用的mask，最小化人脸区域外像素的影响

谢谢大佬回复，在我实验的时候，人脸区域外的背景复杂的时候，背景部分临近帧抖动确实很严重。想问关于人脸部分比如眉毛，眼睛这些部位，如果这些部位临近帧发生抖动，是不是只能依赖网络的结果啊？
