### ISSUE TITLE
the problem of the real-world LQ faces

### ISSUE THREAD

**Issue by CVHW** [yangxy/GPEN#32]
I appreciate your work. Could you release the 1,000 real-world LQ faces as soon as possible?

**Comment by yangxy** [comment]
> I appreciate your work. Could you release the 1,000 real-world LQ faces as soon as possible?

Please send me an email. See #3

**Comment by CVHW** [comment]
All right. Thank you for your reply.




蓝色夜晚的记忆
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yangxy/GPEN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月9日(星期一) 上午10:28
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [yangxy/GPEN] the problem of the real-world LQ faces (#32)





  
I appreciate your work. Could you release the 1,000 real-world LQ faces as soon as possible?
  
Please send me an email. See #3
 
—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
