### ISSUE TITLE
face_enhancement 处理图片的速度非常慢  face_ Enhancement is very slow to process pictures

### ISSUE THREAD

**Issue by wubangjunjava** [yangxy/GPEN#33]
I have a video that is fuzzy. I use GPEN to optimize it. The video generated 405 pictures in total. It took 11 minutes to complete GPEN processing. My graphics card is a quarter of T4 graphics card. How can I optimize the processing speed? Looking forward to your reply?

我有一个视频比较模糊，我使用了GPEN 来优化。视频一共生成了405张图片，GPEN  处理完成耗时 11分钟，我的显卡是 1/4 的 T4 显卡。我该如何优化处理速度？非常期待您的回复?

**Comment by yangxy** [comment]
Please try our lighter model.
