### ISSUE TITLE
Why the learning rate varies for the encoder, the decoder and the discriminator?

### ISSUE THREAD

**Issue by xuewengeophysics** [yangxy/GPEN#48]
Hi. Thanks for your excellent research work.
I have a question why the learning rate varies for the encoder, the decoder and the discriminator?
In my opinion, the discriminator does not use the GAN prior weight, should the LR of discriminator be larger than that of decoder(generator)?

**Comment by yangxy** [comment]
> Hi. Thanks for your excellent research work.
> I have a question why the learning rate varies for the encoder, the decoder and the discriminator?
> In my opinion, the discriminator does not use the GAN prior weight, should the LR of discriminator be larger than that of decoder(generator)?

The discriminator is also part of our GAN prior actually.

**Comment by xuewengeophysics** [comment]
Thank you very much.
