### ISSUE TITLE
will the train code release?

### ISSUE THREAD

**Issue by zhangyunming** [yangxy/GPEN#5]
i have test the model you release, the result is so good. but there is some black points on face sometimes.
will you release the trainning code ?

**Comment by yangxy** [comment]
Not planned yet, probably when GPEN is no long sota.

Turning to the black points, it may be caused by the noise added when degrading HQ faces.

**Comment by yangxy** [comment]
A simplified version of the training code will be released soon.

**Comment by zimenglan-sysu-512** [comment]
hi @yangxy can u share the dataset used int paper for training?
