### ISSUE TITLE
colorization process

### ISSUE THREAD

**Issue by ylepaih** [yangxy/GPEN#6]
Hi yangxy
Thanks for GPEN, we experiment great results in our tests in most of the cases
Some wrinkles around eyes seems to be identify as glasses, but it's maybe due to pretrained datasets

Could you explain how did you get colorization result in your supplementary pdf ?

**Comment by yangxy** [comment]
Thanks for your interest. 

GPEN for face colorization is trained following the strategies and settings in our paper. We only use different training data.

If needed, I will release our pre-trained GPEN for face colorization. Please let me know.

**Comment by ylepaih** [comment]
Hi yangxy
Thanks for your feedback
pre-trained GPEN for face colorization, would be great to compare with a more common colorization solution
Thanks if you could share your pre-trained data

**Comment by yangxy** [comment]
The pre-trained GPEN for face colorization is now available.  It is not well trained due to we did not pay much attention to this issue.

Please have a try and leave your feedback.

**Comment by ylepaih** [comment]
Thanks a lot yangxy
