### ISSUE TITLE
ask for the pretrained model of GPEN-BFR-256-D

### ISSUE THREAD

**Issue by TracelessLe** [yangxy/GPEN#67]
Hi @yangxy, excellent work!  I want to finetune the GPEN-BFR-256 on my dataset recently. And I get the  pretrained model of generator (GPEN-BFR-256) from your shared link, would you please provide the pretrained model of discriminator on the resolution 256 (GPEN-BFR-256-D, such as GPEN-BFR-512-D)? Thanks a lot.

![image](https://user-images.githubusercontent.com/22371026/138550615-cc215913-3db4-4f49-be7d-93a70b67e9ee.png)

**Comment by bnukiki** [comment]
maybe you can try  pretrained checkpoints  model 550000.pt ?   https://github.com/rosinality/stylegan2-pytorch

**Comment by TracelessLe** [comment]
> maybe you can try pretrained checkpoints model 550000.pt ? https://github.com/rosinality/stylegan2-pytorch

tks, I have tried it.

**Comment by lmvgjp** [comment]
hi, how to use model 550000.pt with GPEN? what modifications to make in the code?
thanks
