### ISSUE TITLE
Load None from pretrained checkpoints

### ISSUE THREAD

**Issue by laleh-samadfam** [yangxy/GPEN#71]
Hello, 

I try to run the code for restoring face images and I get this error. I have the GPEN-BFR-512.pth pretrained model in my weight folder. Can you help me see the problem here?

Traceback (most recent call last):
  File "face_enhancement.py", line 113, in <module>
    faceenhancer = FaceEnhancement(size=args.size, model=args.model, use_sr=args.use_sr, sr_model=args.sr_model, channel_multiplier=args.channel_multiplier, narrow=args.narrow)
  File "face_enhancement.py", line 21, in __init__
    self.facedetector = RetinaFaceDetection(base_dir)
  File "/home/GPEN-main/retinaface/retinaface_detection.py", line 27, in __init__
    self.load_model()
  File "/home//GPEN-main/retinaface/retinaface_detection.py", line 61, in load_model
    self.check_keys(pretrained_dict)
  File "/home/GPEN-main/retinaface/retinaface_detection.py", line 41, in check_keys
    assert len(used_pretrained_keys) > 0, 'load NONE from pretrained checkpoint'
AssertionError: load NONE from pretrained checkpoint

**Comment by BIGJUN777** [comment]
I think you need to download the checkpoints of the face detector (RetrnaFace). Have a try.

![image](https://user-images.githubusercontent.com/35102882/141707946-599945e8-260d-44bd-bc95-ce41bdfc3a12.png)

**Comment by laleh-samadfam** [comment]
Well, yes, I also have that model, looks like the code is using RetinaFace-R50, and the problem is still there.

**Comment by laleh-samadfam** [comment]
Thank you!
