### ISSUE TITLE
Is there no x8 scale BFR model? 

### ISSUE THREAD

**Issue by choieq** [yangxy/GPEN#73]
Hi, Thanks for your great work.

I want to ask if there is no x8 scale BFR pretrained-model.

I'm going to compare it with other Face Super-Resolution which super-resolve x8 scale (e.g. 16x16->128x128).

I found, in the paper, x8 BFR result exist. Could you share that?

Thanks,

**Comment by KleinXin** [comment]
same question

**Comment by yangxy** [comment]
In my experiments, I first resized the 16x16 image to 512x512 (1024x1024 in the paper), restored the resized image, and then resized the enhanced image back to 128x128.

**Comment by choieq** [comment]
> In my experiments, I first resized the 16x16 image to 512x512 (1024x1024 in the paper), restored the resized image, and then resized the enhanced image back to 128x128.

thanks for the reply!
