### ISSUE TITLE
When is FaceParse used?

### ISSUE THREAD

**Issue by TaoTeCha** [yangxy/GPEN#75]
I've been using GPEN for about a week now, results are great. But I changed the code a bit and now ParseNet-latest.pth is required when I don't think I had to use it in the past. The results look different as well. The face is restored but now the hair around the face is pixelated, when it wasn't before.

Is face parse assigning a bounding box and not restoring anything outside of it? How do I stop utilizing face parse?

Thanks

**Comment by yangxy** [comment]
Replace line 82 with line 81 in ``face_enhancement.py`` will do it.

**Comment by yangxy** [comment]
Face parsing provides a more accurate mask that minimizes the impact on image background when pasting restored faces back. If you don't need it, simply comment line 82 and uncomment 81 in ``face_enhancement.py``.

**Comment by TaoTeCha** [comment]
> Replace line 82 with line 81 in `face_enhancement.py` will do it.

That did the trick. It looks much better now. 
Any idea what changed? I originally used the colab code, which doesn't even download the ParseNet model. I only made a few small changes, can't say exactly what off the top of my head, but I don't understand what I could have done to make the code now require Parsenet when it didn't earlier.

Thanks for the help.

**Comment by yangxy** [comment]
> > Replace line 82 with line 81 in `face_enhancement.py` will do it.
> 
> That did the trick. It looks much better now. Any idea what changed? I originally used the colab code, which doesn't even download the ParseNet model. I only made a few small changes, can't say exactly what off the top of my head, but I don't understand what I could have done to make the code now require Parsenet when it didn't earlier.
> 
> Thanks for the help.

I will update the colab demo soon.

**Comment by TaoTeCha** [comment]
Ah, I see. It looks like you just added/updated this yesterday.
You may want to make the FaceParser an optional function argument. It made my output a little worse, but I have a plain white background behind my face.

Thanks again.
