### ISSUE TITLE
face_enhancement slowed? 

### ISSUE THREAD

**Issue by GOZARCK** [yangxy/GPEN#79]
It may be a sensation of mine, but with the new implementation "ParseNet-latest.pth" the process of face_enhancement.py has gotten slower?(really slow)
btw I am using "GPEN-BFR-512.pth"
But nice results!
Thanks!

**Comment by yangxy** [comment]
Face parsing is quite time-consuming. If you don't need it, please refer to #75

**Comment by GOZARCK** [comment]
>>Replace line 82 with line 81 in face_enhancement.py will do it.
Thanks you so much!
