### ISSUE TITLE
About batchsize when training

### ISSUE THREAD

**Issue by insomnia250** [yangxy/GPEN#9]
Thanks for sharing. Brilliant work!
I notice that `batchsize` is set to 1 as mentioned in your paper. Is it by design or just some concession to hardware limitation？Thank you

**Comment by jnulzl** [comment]
> Thanks for sharing. Brilliant work!
> I notice that `batchsize` is set to 1 as mentioned in your paper. Is it by design or just some concession to hardware limitation？Thank you

I found the face will be smoothed if batchsize too big. But I'm not sure if is related to batchsize. I changed batchsize to 1 and still training now.

**Comment by yangxy** [comment]
Just some concession to the hardware limitation.

**Comment by lisc199** [comment]
> > Thanks for sharing. Brilliant work!
> > I notice that `batchsize` is set to 1 as mentioned in your paper. Is it by design or just some concession to hardware limitation？Thank you
> 
> I found the face will be smoothed if batchsize too big. But I'm not sure if is related to batchsize. I changed batchsize to 1 and still training now.

Do you have more info about batch size now?

**Comment by yangxy** [comment]
> > > Thanks for sharing. Brilliant work!
> > > I notice that `batchsize` is set to 1 as mentioned in your paper. Is it by design or just some concession to hardware limitation？Thank you
> > 
> > 
> > I found the face will be smoothed if batchsize too big. But I'm not sure if is related to batchsize. I changed batchsize to 1 and still training now.
> 
> Do you have more info about batch size now?

A simplified version of the training code will be released soon. Stay tuned.
