### ISSUE TITLE
Single Face

### ISSUE THREAD

**Issue by blessedcoolant** [yangxy/GPEN#95]
Is it possible to infer only on a single face that has been provided and not every face in the image.

**Comment by yangxy** [comment]
Updated. Make sure `aligned=True` in `face_enhancement.py`.

**Comment by blessedcoolant** [comment]
@yangxy Thanks for the update. But you forgot to update the FaceGAN class to match the new in_size and out_size setting you supply.

**Comment by yangxy** [comment]
updated.

**Comment by blessedcoolant** [comment]
@yangxy The new code throws a _ValueError: not enough values to unpack (expected 2, got 1)_ in _out, __ = self.model(img_t)_ of face_gan.py

**Comment by blessedcoolant** [comment]
@yangxy New error with the new code in _face_gan.py_

**out, __ = self.model(img_t)
ValueError: not enough values to unpack (expected 2, got 1)**
