### ISSUE TITLE
Channel mismatch after concatenating noise code

### ISSUE THREAD

**Issue by mchong6** [yangxy/GPEN#96]
After you pretrain your decoder, during finetuning stage, you are concatenating noise (from your encoder) to the features. In your code you have a feat_multipler to double the channels of the convolution to take into account of that. But how are you loading the weights of the pretrained decoder when the convolution channels don't match up due to the concatenation?

**Comment by Griffin98** [comment]
Same question here.

**Comment by bnukiki** [comment]
Same question here.

**Comment by yangxy** [comment]
The decoder is not the original StyleGAN.

**Comment by mchong6** [comment]
You do not load the original weights at all?
